---
- hosts: all
  tasks:
    - name: Create Network
      community.docker.docker_network:
        name: wordpress

    - name: Deploy Wordpress
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        ports:
          80:80
        volumes:
          -wordpress:/var/www/html
        networks:
          - name : wordpress
        env:
          WORDPRESS_DB_HOST: "db"
          WORDPRESS_DB_USER: "wordpress_user"
          WORDPRESS_DB_PASSWORD: "test123"
          WORDPRESS_DB_NAME: "wordpress_db"
        restart_policy: always

    - name: Deploy MySQL
      community.docker.docker_container:
        name: db
        image: mysql:5.7
        networks:
          -name: wordpress
        volumes:
          -db:/var/lib/mysql
        env:
          MYSQL_DATABASE: "wordpress_db"
          MYSQL_USER: "wordpress_user"
          MYSQL_PASSWORD: "test123"
          MYSQL_RANDOM_ROOT_PASSWORD: '1'
        restart_policy: always
          
