---
- hosts: all
  tasks:
    - name: Deploy container
      community.docker.docker_container:
        name: nginx
        image: nginx
        ports:
          8080:8080
        restart_policy: always